--------------------------------------------------------
--  File created - Thursday-May-21-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ENCOUNTER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ENCOUNTER" 
   (	"ID" NUMBER(*,0), 
	"HEADER" VARCHAR2(20 BYTE), 
	"DETAILS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ENCOUNTER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ENCOUNTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ENCOUNTER_PK" ON "SYSTEM"."ENCOUNTER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ENCOUNTER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ENCOUNTER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ENCOUNTER" ADD CONSTRAINT "ENCOUNTER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
